### ISSUE TITLE
与路径相关的操作可以考虑使用 std::filesystem::path

### ISSUE THREAD

**Issue by ShenMian** [hebohang/HEngine#14]
`std::filesystem::path` 是 C++17 引入的, 用于表示文件路径. 如果能用其替代 `std::string` 应该可以提高代码的可读性.
例如可以简化以下代码:
https://github.com/hebohang/HEngine/blob/41e4568b6511539ac1da6085aa5b643a0fc51b41/Engine/Source/Runtime/Mesh/Mesh.cpp#L46-L47

**Comment by hebohang** [comment]
谢谢反馈，在Readme代码规范的第七条为“默认情况下 std::string 为相对路径，而 std::filesystem::path 为绝对路径，相对路径到绝对路径需要由 AssetManager::GetFullPath() 去获取”。关于是否要全部换掉std::string还在考量中。

这里Mesh的string是我想用相对路径进行处理。

**Comment by ShenMian** [comment]
请问这么做有什么目的吗, 还是只是方便通过类型区分相对路径和绝对路径?
如果使用 `std::filesystem::path` 有很多标准库中的相关函数可以使用, 避免自己在重写一遍.

**Comment by hebohang** [comment]
我主要是方便区分，希望把相对路径保存在组件中，每次使用再通过单例类AssetManager去获取绝对路径。并且我认为有的地方存`string`似乎更加方便，存`std::filesystem::path`我怕碰到字符上的问题（`wchar_t`之类的）以及有的字符处理没有`string`方便，需要转化。而目前我还只支持英文路径。

最后十分感谢您的建议。

**Comment by ShenMian** [comment]
好的, 我理解用于区分的目的. (这方面我是使用变量名来进行区分的)
不过使用 `std::filesystem::path` 在处理不同字符类型时不是更加方便吗? 可以利用成员函数直接转化为 `std::string`/`std::wstring`/`std::u8string`/`std::u16string`/`std::u32string`.

**Comment by hebohang** [comment]
因为我觉得`string`有丰富的方法，如果用`path`需要每次先转为`string`，并且目前我只关心了英文路径，所以暂时只需要`std::string`就足够了。也许未来我会改为`std::filesystem::path`:)
